// src/app/[shopName]/panel/components/PrintableTicket.tsx
import type { PlainPanelOrder } from "../lib/serialize-panel-order";

const DATE_TIME_FORMAT = new Intl.DateTimeFormat("es-AR", {
  dateStyle: "short",
  timeStyle: "short",
});

type PrintableTicketProps = {
  readonly order: PlainPanelOrder;
};

export function PrintableTicket({ order }: PrintableTicketProps) {
  return (
    <div
      data-print-ticket
      className="hidden print:block print:w-[80mm] print:bg-white print:p-[4mm] print:font-mono print:text-xs print:text-black"
    >
      <h1 className="mb-0.5 text-center text-lg font-bold">COMANDA</h1>
      <p className="m-0 text-center text-[11px] text-gray-700">
        {DATE_TIME_FORMAT.format(new Date(order.createdAt))}
      </p>
      <p className="m-0 text-center text-[11px] text-gray-700">
        #{order.externalReference}
      </p>
      <hr className="my-1.5 border-t border-dashed border-black" />
      <p className="m-0 text-[13px] font-bold">{order.customerName}</p>
      {order.customerPhone ? (
        <p className="my-0.5 text-[11px]">Tel: {order.customerPhone}</p>
      ) : null}
      <p className="my-0.5 text-[11px]">
        {order.deliveryMethod === "delivery"
          ? `ENVIO: ${order.address ?? ""}`
          : "RETIRO EN LOCAL"}
      </p>
      <hr className="my-1.5 border-t border-dashed border-black" />
      {order.items.map((item, index) => (
        <TicketItemLine key={`${item.name}-${index}`} item={item} />
      ))}
      <TicketTotals order={order} />
    </div>
  );
}

type TicketItemLineProps = {
  readonly item: PlainPanelOrder["items"][number];
};

function TicketItemLine({ item }: TicketItemLineProps) {
  return (
    <div className="my-0.5">
      <div className="flex gap-1.5 text-[13px]">
        <span className="min-w-6 font-bold">{item.quantity}x</span>
        <span>{item.name}</span>
      </div>
      {item.accessories.map((accessory, index) => (
        <p key={index} className="m-0 ml-7 text-[11px] text-gray-700">
          + {accessory.name}
        </p>
      ))}
    </div>
  );
}

type TicketTotalsProps = {
  readonly order: PlainPanelOrder;
};

function TicketTotals({ order }: TicketTotalsProps) {
  return (
    <div>
      <hr className="my-1.5 border-t border-dashed border-black" />
      {order.deliveryCost > 0 ? (
        <div className="my-0.5 flex justify-between text-xs">
          <span>Envio</span>
          <span>${order.deliveryCost.toLocaleString("es-AR")}</span>
        </div>
      ) : null}
      <div className="my-1 flex justify-between text-[15px] font-bold">
        <span>TOTAL</span>
        <span>${order.total.toLocaleString("es-AR")}</span>
      </div>
      {order.notes ? (
        <p className="m-0 text-[11px] italic">NOTAS: {order.notes}</p>
      ) : null}
    </div>
  );
}

// src/routes/[shopName]/panel/components/printable-ticket.svelte
<script lang="ts">
  import { DeliveryMethod } from '$lib/schemas/order';
  import type { Order } from '$lib/types/order';

  interface Props {
    order: Order;
  }

  const { order }: Props = $props();

  const createdDate = $derived(
    new Intl.DateTimeFormat('es-AR', {
      dateStyle: 'short',
      timeStyle: 'short'
    }).format(new Date(order.createdAt))
  );

  const isDelivery = $derived(
    order.deliveryMethod === DeliveryMethod.enum.delivery
  );
</script>

<div
  class="hidden print:fixed print:top-0 print:left-0 print:block print:w-[80mm] print:bg-white print:p-[4mm] print:font-mono print:text-xs print:text-black"
>
  <h1 class="mb-0.5 text-center text-lg font-bold">COMANDA</h1>
  <p class="m-0 text-center text-[11px] text-gray-700">{createdDate}</p>
  <p class="m-0 text-center text-[11px] text-gray-700">
    #{order.externalReference}
  </p>

  <hr class="my-1.5 border-0 border-t border-dashed border-black" />

  <p class="m-0 text-[13px] font-bold">{order.customerName}</p>
  {#if order.customerPhone}
    <p class="my-0.5 text-[11px]">Tel: {order.customerPhone}</p>
  {/if}

  {#if isDelivery}
    <p class="my-0.5 text-[11px]">ENVIO: {order.address ?? ''}</p>
  {:else}
    <p class="my-0.5 text-[11px]">RETIRO EN LOCAL</p>
  {/if}

  <hr class="my-1.5 border-0 border-t border-dashed border-black" />

  {#each order.items as item, i (i)}
    <div class="my-0.5 flex gap-1.5 text-[13px]">
      <span class="min-w-6 font-bold">{item.quantity}x</span>
      <span>{item.name}</span>
    </div>
    {#if item.accessories?.length}
      {#each item.accessories as acc, j (j)}
        <p class="m-0 ml-7 text-[11px] text-gray-700">+ {acc.name}</p>
      {/each}
    {/if}
  {/each}

  <hr class="my-1.5 border-0 border-t border-dashed border-black" />

  {#if order.deliveryCost > 0}
    <div class="my-0.5 flex justify-between text-xs">
      <span>Envio</span>
      <span>${order.deliveryCost.toLocaleString('es-AR')}</span>
    </div>
  {/if}

  <div class="my-1 flex justify-between text-[15px] font-bold">
    <span>TOTAL</span>
    <span>${order.total.toLocaleString('es-AR')}</span>
  </div>

  {#if order.notes}
    <hr class="my-1.5 border-0 border-t border-dashed border-black" />
    <p class="m-0 text-[11px] italic">NOTAS: {order.notes}</p>
  {/if}
</div>

<style>
  @media print {
    @page {
      margin: 0;
    }

    :global(body *) {
      visibility: hidden !important;
    }

    div,
    div * {
      visibility: visible !important;
    }
  }
</style>
