// src/routes/[shopName]/pedir/[productId]/+page.svelte
<script lang="ts">
  import { ArrowLeft } from '@lucide/svelte';

  import { cart } from '$lib/cart.svelte';
  import type { PageData } from './$types';
  import ProductImageCarousel from './components/product-image-carousel.svelte';
  import ProductInfoCard from './components/product-info-card.svelte';

  let { data }: { data: PageData } = $props();

  const { product, shopName } = data;

  let quantity = $derived(cart.getQuantity(product.id));

  function handleAdd() {
    cart.add(product);
    navigator.vibrate?.(10);
  }
</script>

<div class="flex min-h-screen flex-col bg-[#E0E0E0] md:bg-white">
  <div class="px-5 pt-5 pb-2 md:mx-auto md:w-full md:max-w-5xl">
    <a href="/{shopName}/pedir" class="inline-flex">
      <ArrowLeft class="h-5 w-5 text-zinc-400" />
    </a>
  </div>

  <div
    class="flex flex-col md:mx-auto md:w-full md:max-w-5xl md:flex-row md:gap-12 md:px-8 md:py-8"
  >
    <ProductImageCarousel images={product.images} productName={product.name} />

    <ProductInfoCard
      name={product.name}
      category={product.category}
      description={product.description}
      price={product.price}
      {quantity}
      onAdd={handleAdd}
    />
  </div>
</div>

// src/app/[shopName]/pedir/[productId]/page.tsx
import { notFound } from "next/navigation";

import { getShopCatalog } from "../queries";
import { ProductImageCarousel } from "./components/ProductImageCarousel";
import { ProductInfoCard } from "./components/ProductInfoCard";
import { getShopItemDetail } from "./queries";

export const revalidate = 30;

export default async function ProductDetailPage({
  params,
}: {
  params: Promise<{ shopName: string; productId: string }>;
}) {
  const { shopName, productId } = await params;
  const productIdNumber = Number(productId);

  if (Number.isNaN(productIdNumber)) {
    notFound();
  }

  const [{ catalog }, { shopItem }] = await Promise.all([
    getShopCatalog(shopName),
    getShopItemDetail(productIdNumber),
  ]);

  if (!catalog || !shopItem) {
    notFound();
  }

  const belongsToShop = shopItem.item.shopId === catalog.shop.id;

  if (!belongsToShop) {
    notFound();
  }

  return (
    <main className="flex min-h-screen flex-col bg-[#E0E0E0] md:bg-white">
      <div className="px-5 pt-5 pb-2 md:mx-auto md:w-full md:max-w-5xl">
        <a
          href={`/${shopName}/pedir`}
          className="inline-flex"
          data-testid="product-back-link"
        >
          <span aria-hidden>←</span>
          <span className="sr-only">Back to menu</span>
        </a>
      </div>

      <div className="flex flex-col md:mx-auto md:w-full md:max-w-5xl md:flex-row md:gap-12 md:px-8 md:py-8">
        <ProductImageCarousel
          images={shopItem.item.images}
          productName={shopItem.item.name}
        />
        <ProductInfoCard
          id={shopItem.item.id}
          name={shopItem.item.name}
          category={shopItem.item.category}
          description={shopItem.item.description}
          price={shopItem.item.price}
        />
      </div>
    </main>
  );
}
