// src/app/[shopName]/pedir/components/ShopHeader.tsx
import type { Shop } from "@/domain/entities/shop.entity";
import { ShopBanner } from "./ShopBanner";
import { ShopInfo } from "./ShopInfo";

type ShopHeaderProps = {
  readonly shop: Shop;
  readonly shopName: string;
};

export function ShopHeader({ shop, shopName }: ShopHeaderProps) {
  const name = shop.displayName ?? shopName;

  return (
    <header className="relative">
      <ShopBanner
        name={name}
        portraitUrl={shop.portraitUrl}
        logoUrl={shop.logoUrl}
      />
      <ShopInfo name={name} address={shop.address} openHours={shop.openHours} />
    </header>
  );
}

// src/routes/[shopName]/pedir/components/shop-header.svelte
<script lang="ts">
  import ShopBanner from './shop-banner.svelte';
  import ShopInfo from './shop-info.svelte';

  interface ShopHeaderProps {
    shop: {
      address: string | null;
      displayName: string | null;
      logoUrl: string | null;
      portraitUrl: string | null;
      openHours: string | null;
    };
    shopName: string;
  }

  const { shop, shopName }: ShopHeaderProps = $props();

  const name = $derived(shop.displayName ?? shopName);
</script>

<header class="relative">
  <ShopBanner {name} portraitUrl={shop.portraitUrl} logoUrl={shop.logoUrl} />
  <ShopInfo {name} address={shop.address} openHours={shop.openHours} />
</header>
