// src/app/pedido/[id]/components/ReceiptCard.tsx
import { AR_LOCALE } from "@/lib/utils/format";

import { ReceiptRow } from "./receipt-row";

const DATE_TIME_FORMAT = new Intl.DateTimeFormat(AR_LOCALE, {
  dateStyle: "medium",
  timeStyle: "short",
});

const PRICE_FORMAT = new Intl.NumberFormat(AR_LOCALE, {
  style: "currency",
  currency: "ARS",
  minimumFractionDigits: 0,
});

type ReceiptCardItem = {
  readonly name: string;
  readonly quantity: number;
  readonly unitPrice: number;
};

type ReceiptCardProps = {
  readonly id: string;
  readonly nombre: string;
  readonly date: Date;
  readonly notas: string | null;
  readonly items: readonly ReceiptCardItem[];
  readonly total: number;
};

export function ReceiptCard({
  id,
  nombre,
  date,
  notas,
  items,
  total,
}: ReceiptCardProps) {
  return (
    <div className="flex flex-col gap-4 rounded-lg border border-zinc-200 p-4">
      <div className="flex items-center gap-2 border-b border-zinc-100 pb-3">
        <svg
          className="h-4 w-4 text-zinc-500"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          aria-hidden="true"
        >
          <path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z" />
          <path d="M8 7h8M8 11h8M8 15h4" />
        </svg>
        <span className="text-xs font-semibold tracking-wider text-zinc-500 uppercase">
          Recibo
        </span>
      </div>
      <div className="flex flex-col gap-2">
        <ReceiptRow label="Pedido" value={id} mono />
        <ReceiptRow label="Nombre" value={nombre} />
        <ReceiptRow label="Fecha" value={DATE_TIME_FORMAT.format(date)} />
        {notas ? <ReceiptRow label="Notas" value={notas} /> : null}
      </div>
      <div className="flex flex-col gap-2 border-t border-zinc-100 pt-3">
        {items.map((item) => (
          <div key={item.name} className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="font-mono text-xs text-zinc-500">
                {item.quantity}x
              </span>
              <span className="text-sm text-zinc-950">{item.name}</span>
            </div>
            <span className="text-sm text-zinc-950">
              {PRICE_FORMAT.format(item.unitPrice * item.quantity)}
            </span>
          </div>
        ))}
        <div className="flex items-center justify-between border-t border-zinc-100 pt-2">
          <span className="text-sm font-medium text-zinc-950">Total</span>
          <span className="text-sm font-semibold text-zinc-950">
            {PRICE_FORMAT.format(total)}
          </span>
        </div>
      </div>
    </div>
  );
}

// src/routes/pedido/[id]/components/receipt-card.svelte
<script lang="ts">
  import Receipt from '@lucide/svelte/icons/receipt';

  import { formatPrice } from '$lib/utils';

  interface Props {
    id: string;
    nombre: string;
    date: Date;
    notas?: string;
    items: Array<{ name: string; quantity: number; unitPrice: number }>;
    total: number;
  }

  let { id, nombre, date, notas, items, total }: Props = $props();

  function formatDate(d: Date): string {
    return new Intl.DateTimeFormat('es-AR', {
      dateStyle: 'medium',
      timeStyle: 'short'
    }).format(d);
  }
</script>

<div class="flex flex-col gap-4 rounded-lg border border-zinc-200 p-4">
  <div class="flex items-center gap-2 border-b border-zinc-100 pb-3">
    <Receipt class="h-4 w-4 text-zinc-500" />
    <span class="text-xs font-semibold tracking-wider text-zinc-500 uppercase"
      >Recibo</span
    >
  </div>

  <div class="flex flex-col gap-2">
    <div class="flex items-center justify-between">
      <span class="text-xs text-zinc-500">Pedido</span>
      <span class="font-mono text-xs text-zinc-950">{id}</span>
    </div>
    <div class="flex items-center justify-between">
      <span class="text-xs text-zinc-500">Nombre</span>
      <span class="text-xs text-zinc-950">{nombre}</span>
    </div>
    <div class="flex items-center justify-between">
      <span class="text-xs text-zinc-500">Fecha</span>
      <span class="text-xs text-zinc-950">{formatDate(date)}</span>
    </div>
    {#if notas}
      <div class="flex items-start justify-between gap-4">
        <span class="text-xs text-zinc-500">Notas</span>
        <span class="text-right text-xs text-zinc-950">{notas}</span>
      </div>
    {/if}
  </div>

  <div class="flex flex-col gap-2 border-t border-zinc-100 pt-3">
    {#each items as item (item.name)}
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-2">
          <span class="font-mono text-xs text-zinc-500">{item.quantity}x</span>
          <span class="text-sm text-zinc-950">{item.name}</span>
        </div>
        <span class="font-mono text-sm text-zinc-950">
          {formatPrice(item.unitPrice * item.quantity)}
        </span>
      </div>
    {/each}
  </div>

  <div class="flex items-center justify-between border-t border-zinc-200 pt-3">
    <span class="text-sm font-semibold text-zinc-950">Total</span>
    <span class="font-mono text-base font-semibold text-zinc-950">
      {formatPrice(total)}
    </span>
  </div>
</div>
