// src/routes/[shopName]/pedir/components/category-nav.svelte
<script lang="ts">
  import type { ShopItemCategory as ShopItemCategoryType } from '$lib/types/product';
  import type { GroupedCategory } from '../page.state.svelte';

  interface Props {
    groupedCategories: GroupedCategory[];
    activeCategory: ShopItemCategoryType | null;
    onCategoryClick: (key: ShopItemCategoryType) => void;
  }

  const { groupedCategories, activeCategory, onCategoryClick }: Props =
    $props();
</script>

<div
  class="scrollbar-hide sticky top-0 z-10 flex gap-2 overflow-x-auto bg-[#F5F5F5] px-4 py-3 md:flex-wrap md:justify-center"
>
  {#each groupedCategories as { key, label, emoji } (key)}
    <button
      class="shrink-0 rounded-full px-4 py-1.5 text-sm font-medium transition-colors {activeCategory ===
      key
        ? 'bg-zinc-900 text-white'
        : ' text-zinc-600 hover:text-zinc-900'}"
      onclick={() => onCategoryClick(key)}
    >
      {emoji}
      {label}
    </button>
  {/each}
</div>

// src/app/[shopName]/pedir/components/CategoryNav.tsx
"use client";

import { useActiveCategory } from "../hooks/useActiveCategory";

type CategorySummary = {
  readonly key: string;
  readonly label: string;
  readonly emoji: string;
};

type CategoryNavProps = {
  readonly categories: readonly CategorySummary[];
};

export function CategoryNav({ categories }: CategoryNavProps) {
  const activeCategory = useActiveCategory(categories.map((c) => c.key));

  return (
    <div className="scrollbar-hide sticky top-0 z-10 flex gap-2 overflow-x-auto bg-[#F5F5F5] px-4 py-3 md:flex-wrap md:justify-center">
      {categories.map(({ key, label, emoji }) => (
        <button
          key={key}
          type="button"
          data-testid={`category-nav-${key}`}
          onClick={() => {
            document
              .getElementById(key)
              ?.scrollIntoView({ behavior: "smooth" });
          }}
          className={`shrink-0 rounded-full px-4 py-1.5 text-sm font-medium transition-colors ${
            activeCategory === key
              ? "bg-zinc-900 text-white"
              : "text-zinc-600 hover:text-zinc-900"
          }`}
        >
          {emoji} {label}
        </button>
      ))}
    </div>
  );
}
